Repository odigos-io/odigos, pull requests merged in 2025-02, with the labels that each got.

#2364 fix: replace IBM Sarama URL in docs to fix check-links
  docs/instrumentations/golang/ebpf.mdx
Labels: documentation

#2367 chore: bump deps in nodejs server of workload-lifecycle
  tests/e2e/workload-lifecycle/services/nodejs-http-server/package.json
  tests/e2e/workload-lifecycle/services/nodejs-http-server/yarn.lock
Labels: dependencies, javascript, vulnerability

#2361 set PR_URL as env var in enterprise dependencies workflow
  .github/workflows/trigger-odigos-enterprise.yaml
Labels: cicd

#2374 Replace OpenShift docs URL with Odigos catalog on OpenShift
  docs/setup/system-requirements.mdx
Labels: documentation

#2370 [GEN-2302]: watch for modified events, do not toast them
  frontend/kube/watchers/instrumentation_config_watcher.go
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/notification/useSSE.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/utils/constants/string.tsx
Labels: enhancement, frontend

#2371 [GEN-2303]: fix loader for namespace-sources
  frontend/webapp/containers/main/sources/choose-sources/choose-sources-body/choose-sources-body-fast/sources-list/index.tsx
Labels: bug, frontend

#2380 Fix UI crash
  frontend/graph/schema.resolvers.go
  frontend/webapp/app/layout.tsx
  frontend/webapp/components/app-error-boundary/index.tsx
  frontend/webapp/components/common/dropdowns/error-dropdown/index.tsx
  frontend/webapp/components/index.ts
  frontend/webapp/package.json
  frontend/webapp/types/actions.ts
  frontend/webapp/types/destinations.ts
  frontend/webapp/types/sources.ts
  frontend/webapp/yarn.lock
Labels: bug, frontend

#2389 fix: sperate cli namespace flag for sources and install
  cli/cmd/sources.go
Labels: bug

#2384 feat: add tests to verify node label is added as expected
  tests/common/assert/node-odiglet-label.yaml
  tests/e2e/helm-chart/chainsaw-test.yaml
  tests/e2e/multi-apps/chainsaw-test.yaml
  tests/e2e/workload-lifecycle/chainsaw-test.yaml
Labels: cicd

#2387 ci: Add 'odigos-test' namespace for CLI installation
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/cypress/e2e/05-actions.cy.ts
  frontend/webapp/cypress/e2e/06-rules.cy.ts
  tests/e2e/ui/chainsaw-test.yaml
Labels: cicd

#2386 Bump OpenTelemetry Collector dependencies to 0.119.0
  Makefile
  api/go.mod
  api/go.sum
  autoscaler/go.mod
  autoscaler/go.sum
  cli/go.mod
  cli/go.sum
  collector/Makefile
  collector/builder-config.yaml
  collector/exporters/azureblobstorageexporter/go.mod
  collector/exporters/azureblobstorageexporter/go.sum
  collector/exporters/googlecloudstorageexporter/go.mod
  collector/exporters/googlecloudstorageexporter/go.sum
  collector/exporters/mockdestinationexporter/go.mod
  collector/exporters/mockdestinationexporter/go.sum
  collector/internal/tools/go.mod
  collector/internal/tools/go.sum
  collector/odigosotelcol/components.go
  collector/odigosotelcol/go.mod
  collector/odigosotelcol/go.sum
  collector/odigosotelcol/main.go
  collector/processors/odigosconditionalattributes/generated_component_test.go
  collector/processors/odigosconditionalattributes/go.mod
  collector/processors/odigosconditionalattributes/go.sum
  collector/processors/odigosresourcenameprocessor/generated_component_test.go
  collector/processors/odigosresourcenameprocessor/go.mod
  collector/processors/odigosresourcenameprocessor/go.sum
  collector/processors/odigossamplingprocessor/generated_component_test.go
  collector/processors/odigossamplingprocessor/go.mod
  collector/processors/odigossamplingprocessor/go.sum
  collector/processors/odigossourcesfilterprocessor/generated_component_test.go
  collector/processors/odigossourcesfilterprocessor/go.mod
  collector/processors/odigossourcesfilterprocessor/go.sum
  collector/processors/odigossqldboperationprocessor/generated_component_test.go
  collector/processors/odigossqldboperationprocessor/go.mod
  collector/processors/odigossqldboperationprocessor/go.sum
  collector/processors/odigostrafficmetrics/generated_component_test.go
  collector/processors/odigostrafficmetrics/go.mod
  collector/processors/odigostrafficmetrics/go.sum
  collector/processors/odigostrafficmetrics/internal/metadata/generated_telemetry.go
  collector/processors/odigostrafficmetrics/internal/metadatatest/generated_telemetrytest.go
  collector/processors/odigostrafficmetrics/internal/metadatatest/generated_telemetrytest_test.go
  collector/providers/odigosfileprovider/go.mod
  collector/providers/odigosfileprovider/go.sum
  frontend/go.mod
  frontend/go.sum
  instrumentor/go.mod
  instrumentor/go.sum
  k8sutils/go.mod
  k8sutils/go.sum
  odiglet/go.mod
  odiglet/go.sum
  opampserver/go.mod
  opampserver/go.sum
  scheduler/go.mod
  scheduler/go.sum
  scripts/cli-docgen/go.mod
  scripts/cli-docgen/go.sum
Labels: dependencies, go

#2390 [GEN-2322] chore: config set command doc
  cli/cmd/config.go
  docs/cli/odigos_config.mdx
  docs/mint.json
  docs/sync-dest-doc.py
Labels: documentation

#2383 reduce fp nodejs runtime inspection
  procdiscovery/pkg/inspectors/nodejs/nodejs.go
Labels: enhancement

#2404 fix: use retry watchers is UI
  frontend/kube/watchers/destination_watcher.go
  frontend/kube/watchers/instrumentation_config_watcher.go
  frontend/kube/watchers/instrumentation_instance_watcher.go
  frontend/services/collector_metrics/watchers.go
Labels: frontend

#2407 refactor: migrate otel resource env to distro
  distros/distro/oteldistribution.go
  distros/yamls/dotnet-community.yaml
  distros/yamls/dotnet-legacy.yaml
  distros/yamls/java-community.yaml
  distros/yamls/java-ebpf-instrumentations.yaml
  distros/yamls/java-enterprise.yaml
  distros/yamls/nodejs-community.yaml
  distros/yamls/nodejs-enterprise.yaml
  distros/yamls/python-community.yaml
  distros/yamls/python-enterprise.yaml
  instrumentor/controllers/agentenabled/pods_webhook.go
  instrumentor/controllers/agentenabled/podswebhook/env.go
  instrumentor/controllers/agentenabled/podswebhook/otelresource.go
Labels: enhancement

#2409 fix: recreate autoscaler resources if deleted or modified
  autoscaler/controllers/collectorsgroup_controller.go
Labels: bug

#2408 feat: add a status condition to ic for instrumentation details
  api/odigos/v1alpha1/instrumentationconfig_types.go
  instrumentor/controllers/agentenabled/sync.go
  instrumentor/controllers/deleteinstrumentationconfig/common.go
  instrumentor/controllers/deleteinstrumentationconfig/instrumentationconfig_controller.go
  instrumentor/controllers/deleteinstrumentationconfig/namespace_controller.go
  instrumentor/controllers/deleteinstrumentationconfig/source_controller.go
  instrumentor/controllers/startlangdetection/common.go
  instrumentor/controllers/startlangdetection/conditionutils.go
  instrumentor/controllers/startlangdetection/namespace_controller.go
  instrumentor/controllers/startlangdetection/source_controller.go
  instrumentor/controllers/startlangdetection/workload_controllers.go
  k8sutils/pkg/source/source.go
  tests/e2e/workload-lifecycle/01-assert-instrumented.yaml
Labels: enhancement

#2405 odiglet: Initialize clientset at startup and do OpenShift selinux changes last
  k8sutils/pkg/node/node.go
  odiglet/cmd/main.go
  odiglet/odiglet.go
  odiglet/pkg/instrumentation/fs/agents.go
Labels: bug

#2423 [GEN-2343]: add K8sAttributes action to Frontend
  frontend/graph/generated.go
  frontend/graph/model/models_gen.go
  frontend/graph/schema.graphqls
  frontend/graph/schema.resolvers.go
  frontend/services/actions/addclusterinfo.go
  frontend/services/actions/constants.go
  frontend/services/actions/k8sattributes.go
  frontend/webapp/@types/actions.ts
  frontend/webapp/app/(setup)/choose-sources/page.tsx
  frontend/webapp/components/lib-imports/setup-header.tsx
  frontend/webapp/graphql/queries/compute-platform.ts
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
Labels: enhancement, frontend

#2431 Add access_token to artifact_registry workflow
  .github/workflows/publish-modules-artifactregistry.yml
Labels: cicd

#2433 [GEN-1959]: add IBM Instana destination
  common/config/instana.go
  common/config/root.go
  common/config/utils.go
  common/dests.go
  destinations/data/instana.yaml
  destinations/logos/instana.svg
  docs/adding-new-dest.mdx
  docs/backends-overview.mdx
  docs/backends/instana.mdx
  docs/mint.json
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
Labels: destinations

#2428 [GEN-2347]: add Kafka destination
  .golangci.yml
  common/config/kafka.go
  common/config/root.go
  common/config/utils.go
  common/dests.go
  destinations/data/kafka.yaml
  destinations/logos/kafka.svg
  docs/backends-overview.mdx
  docs/backends/kafka.mdx
  docs/mint.json
Labels: destinations

#2436 Use docker/login-action@v3 for artifact registry workflow
  .github/workflows/publish-modules-artifactregistry.yml
Labels: cicd

#2449 Fix: UI favicon, conditions layout, namespace selection
  frontend/graph/generated.go
  frontend/graph/model/models_gen.go
  frontend/graph/schema.graphqls
  frontend/services/config.go
  frontend/webapp/@types/config.ts
  frontend/webapp/app/(setup)/choose-destination/page.tsx
  frontend/webapp/app/(setup)/choose-sources/page.tsx
  frontend/webapp/app/layout.tsx
  frontend/webapp/app/overview/page.tsx
  frontend/webapp/app/page.tsx
  frontend/webapp/components/lib-imports/overview-header.tsx
  frontend/webapp/components/lib-imports/overview-main.tsx
  frontend/webapp/components/lib-imports/overview-modals-and-drawers.tsx
  frontend/webapp/components/providers/page-container.tsx
  frontend/webapp/components/styled.tsx
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/cypress/e2e/05-actions.cy.ts
  frontend/webapp/cypress/e2e/06-rules.cy.ts
  frontend/webapp/graphql/queries/config.ts
  frontend/webapp/hooks/compute-platform/usePaginatedSources.ts
  frontend/webapp/hooks/config/useConfig.ts
  frontend/webapp/hooks/describe/useDescribeOdigos.ts
  frontend/webapp/hooks/describe/useDescribeSource.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/public/manifest.json
  frontend/webapp/yarn.lock
Labels: bug, frontend

#2443 fix: destinations doc script - image sizes, and custom content demo text
  docs/backends-overview.mdx
  docs/backends/appdynamics.mdx
  docs/backends/awss3.mdx
  docs/backends/axiom.mdx
  docs/backends/azureblob.mdx
  docs/backends/betterstack.mdx
  docs/backends/causely.mdx
  docs/backends/chronosphere.mdx
  docs/backends/clickhouse.mdx
  docs/backends/coralogix.mdx
  docs/backends/dash0.mdx
  docs/backends/datadog.mdx
  docs/backends/dynatrace.mdx
  docs/backends/elasticapm.mdx
  docs/backends/elasticsearch.mdx
  docs/backends/gigapipe.mdx
  docs/backends/googlecloudmonitoring.mdx
  docs/backends/grafanacloudloki.mdx
  docs/backends/grafanacloudprometheus.mdx
  docs/backends/grafanacloudtempo.mdx
  docs/backends/groundcover.mdx
  docs/backends/honeycomb.mdx
  docs/backends/hyperdx.mdx
  docs/backends/instana.mdx
  docs/backends/jaeger.mdx
  docs/backends/kafka.mdx
  docs/backends/kloudmate.mdx
  docs/backends/last9.mdx
  docs/backends/lightstep.mdx
  docs/backends/logzio.mdx
  docs/backends/loki.mdx
  docs/backends/lumigo.mdx
  docs/backends/middleware.mdx
  docs/backends/newrelic.mdx
  docs/backends/opsverse.mdx
  docs/backends/otlp.mdx
  docs/backends/otlphttp.mdx
  docs/backends/prometheus.mdx
  docs/backends/qryn.mdx
  docs/backends/quickwit.mdx
  docs/backends/signoz.mdx
  docs/backends/splunk.mdx
  docs/backends/sumologic.mdx
  docs/backends/tempo.mdx
  docs/backends/traceloop.mdx
  docs/backends/uptrace.mdx
  docs/sync-dest-doc.py
Labels: documentation

#2444 [GEN-2356]: add AWS CloudWatch destination
  collector/builder-config.yaml
  collector/odigosotelcol/components.go
  collector/odigosotelcol/go.mod
  collector/odigosotelcol/go.sum
  common/config/awscloudwatch.go
  common/config/awss3.go
  common/config/instana.go
  common/config/kafka.go
  common/config/root.go
  common/dests.go
  destinations/data/awscloudwatch.yaml
  destinations/data/awss3.yaml
  destinations/data/kafka.yaml
  destinations/logos/awscloudwatch.svg
  destinations/logos/awss3.svg
  destinations/logos/s3.svg
  docs/backends-overview.mdx
  docs/backends/awscloudwatch.mdx
  docs/backends/awss3.mdx
  docs/backends/elasticsearch.mdx
  docs/backends/jaeger.mdx
  docs/backends/kafka.mdx
  docs/mint.json
  docs/sync-dest-doc.py
Labels: destinations

#2461 Bump UI deps, make relevant adjustments
  frontend/webapp/.eslintrc.json
  frontend/webapp/README.md
  frontend/webapp/app/layout.tsx
  frontend/webapp/components/lib-imports/overview-header.tsx
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/next.config.ts
  frontend/webapp/package.json
  frontend/webapp/utils/constants/index.ts
  frontend/webapp/utils/constants/routes.tsx
  frontend/webapp/utils/constants/urls.tsx
  frontend/webapp/yarn.lock
Labels: frontend

#2394 Add RHEL dockerfiles to regular build CI
  .github/workflows/build.yaml
Labels: cicd

#2473 Enrich UI E2E tests
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/01-connection.cy.ts
  frontend/webapp/cypress/e2e/02-onboarding.cy.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/cypress/e2e/05-actions.cy.ts
  frontend/webapp/cypress/e2e/06-rules.cy.ts
  frontend/webapp/cypress/functions/index.ts
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
  tests/e2e/ui/chainsaw-test.yaml
Labels: enhancement, frontend, cicd

#2477 Fix UI performance issues
  Makefile
  frontend/gqlgen.yml
  frontend/graph/generated.go
  frontend/graph/model/models_gen.go
  frontend/graph/schema.graphqls
  frontend/graph/schema.resolvers.go
  frontend/kube/watchers/instrumentation_config_watcher.go
  frontend/kube/watchers/instrumentation_instance_watcher.go
  frontend/main.go
  frontend/webapp/@types/compute-platform.ts
  frontend/webapp/@types/destinations.ts
  frontend/webapp/components/lib-imports/overview-main.tsx
  frontend/webapp/graphql/queries/compute-platform.ts
  frontend/webapp/graphql/queries/destination.ts
  frontend/webapp/graphql/queries/index.ts
  frontend/webapp/graphql/queries/source.ts
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/compute-platform/index.ts
  frontend/webapp/hooks/compute-platform/usePaginatedSources.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/hooks/notification/useSSE.ts
  frontend/webapp/hooks/overview/useMetrics.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/store/usePaginatedStore.ts
  frontend/webapp/yarn.lock
Labels: bug, frontend

#2492 Prevent fail fast in cross cloud providers
  .github/workflows/cross-cloud-tests.yaml
Labels: bug, cicd

#2489 fix: data-flow flickering on re-renders
  frontend/graph/resolver.go
  frontend/graph/schema.resolvers.go
  frontend/main.go
  frontend/webapp/@types/sources.ts
  frontend/webapp/components/lib-imports/overview-header.tsx
  frontend/webapp/cypress/functions/index.ts
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/hooks/notification/useSSE.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/store/usePaginatedStore.ts
  frontend/webapp/yarn.lock
  tests/e2e/workload-lifecycle/chainsaw-test.yaml
Labels: bug, frontend

#2502 Add "focused entity" pages to UI
  frontend/webapp/app/(overview)/actions/page.tsx
  frontend/webapp/app/(overview)/destinations/page.tsx
  frontend/webapp/app/(overview)/instrumentation-rules/page.tsx
  frontend/webapp/app/(overview)/layout.tsx
  frontend/webapp/app/(overview)/overview/page.tsx
  frontend/webapp/app/(overview)/sources/page.tsx
  frontend/webapp/app/(setup)/choose-destination/page.tsx
  frontend/webapp/app/(setup)/choose-sources/page.tsx
  frontend/webapp/app/(setup)/layout.tsx
  frontend/webapp/app/overview/page.tsx
  frontend/webapp/app/page.tsx
  frontend/webapp/components/index.ts
  frontend/webapp/components/lib-imports/error-boundary.tsx
  frontend/webapp/components/lib-imports/index.ts
  frontend/webapp/components/lib-imports/overview-header.tsx
  frontend/webapp/components/lib-imports/overview-main.tsx
  frontend/webapp/components/lib-imports/overview-modals-and-drawers.tsx
  frontend/webapp/components/lib-imports/setup-header.tsx
  frontend/webapp/components/providers/page-container.tsx
  frontend/webapp/cypress.config.ts
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/cypress/e2e/05-actions.cy.ts
  frontend/webapp/cypress/e2e/06-rules.cy.ts
  frontend/webapp/cypress/functions/index.ts
  frontend/webapp/hooks/compute-platform/useNamespace.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/utils/constants/routes.tsx
  frontend/webapp/yarn.lock
Labels: enhancement, frontend
