Repository odigos-io/odigos, pull requests merged in 2025-03, with the labels that each got.

#2515 [GEN-2387]: fix UI config
  frontend/services/config.go
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
Labels: bug, frontend

#2512 Remove "refetch" after CRUD operations in UI
  frontend/kube/watchers/destination_watcher.go
  frontend/kube/watchers/instrumentation_config_watcher.go
  frontend/services/actions/k8sattributes.go
  frontend/services/instrumentationrule.go
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/cypress/e2e/06-rules.cy.ts
  frontend/webapp/graphql/mutations/action.ts
  frontend/webapp/graphql/mutations/destination.ts
  frontend/webapp/graphql/mutations/instrumentation-rule.ts
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/store/usePaginatedStore.ts
Labels: bug, frontend

#2508 UI - fix filter crash + minor performance tweaks
  common/odigos_config.go
  frontend/graph/schema.resolvers.go
  frontend/kube/watchers/instrumentation_config_watcher.go
  frontend/services/utils.go
  frontend/webapp/components/providers/apollo-provider.tsx
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/functions/index.ts
  frontend/webapp/hooks/describe/useDescribeOdigos.ts
  frontend/webapp/hooks/describe/useDescribeSource.ts
  frontend/webapp/hooks/overview/useMetrics.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  helm/odigos/templates/odigos-config-cm.yaml
  helm/odigos/values.yaml
Labels: bug, frontend

#2518 fix: operator in release CI
  .github/workflows/publish-modules-artifactregistry.yml
  .github/workflows/publish-modules.yml
Labels: cicd

#2495 Move workload lifecycle to ecr
  Makefile
  tests/e2e/workload-lifecycle/01-assert-workloads.yaml
  tests/e2e/workload-lifecycle/01-install-test-apps.yaml
  tests/e2e/workload-lifecycle/02-assert-workload-update.yaml
  tests/e2e/workload-lifecycle/02-update-workload-manifests.yaml
  tests/e2e/workload-lifecycle/chainsaw-test.yaml
Labels: cicd

#2519 UI - updated describe, table sorting, conditions "disabled" status
  api/odigos/v1alpha1/instrumentationconfig_types.go
  frontend/graph/conversions.go
  frontend/graph/model/models_gen.go
  frontend/graph/schema.graphqls
  frontend/services/sources.go
  frontend/webapp/@types/actions.ts
  frontend/webapp/@types/destinations.ts
  frontend/webapp/@types/sources.ts
  frontend/webapp/app/(overview)/actions/page.tsx
  frontend/webapp/app/(overview)/destinations/page.tsx
  frontend/webapp/app/(overview)/instrumentation-rules/page.tsx
  frontend/webapp/app/(overview)/layout.tsx
  frontend/webapp/app/(overview)/overview/page.tsx
  frontend/webapp/app/(overview)/sources/page.tsx
  frontend/webapp/components/lib-imports/overview-header.tsx
  frontend/webapp/components/lib-imports/overview-modals-and-drawers.tsx
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/store/index.ts
  frontend/webapp/store/usePaginatedStore.ts
  frontend/webapp/yarn.lock
  instrumentor/controllers/agentenabled/rollout/rollout.go
Labels: enhancement, frontend

#2538 fix: use vpid in e2e test assert after agent merge
  tests/common/assert/simple-demo-instrumented.yaml
  tests/e2e/workload-lifecycle/01-assert-instrumented.yaml
Labels: cicd

#2536 GKE detect workaround
  autoscaler/cmd/main.go
  autoscaler/controllers/controller_config/controller_config.go
  autoscaler/controllers/datacollection/configmap.go
  autoscaler/go.mod
  autoscaler/go.sum
Labels: bug

#2532 Add diagnose output to cli upgrade
  .github/workflows/e2e.yaml
  tests/e2e/workload-lifecycle/chainsaw-test.yaml
Labels: cicd

#2458 feat: add internalTrafficPolicy data collection service for agents telemetry export
  .github/workflows/e2e.yaml
  api/k8sconsts/nodecollector.go
  autoscaler/Makefile
  autoscaler/cmd/main.go
  autoscaler/controllers/collectorsgroup_controller.go
  autoscaler/controllers/controller_config/controller_config.go
  autoscaler/controllers/datacollection/daemonset.go
  autoscaler/controllers/datacollection/root.go
  autoscaler/controllers/datacollection/service.go
  autoscaler/controllers/instrumentedapplication_controller.go
  autoscaler/controllers/processor_controller.go
  autoscaler/migration.go
  helm/odigos/templates/odiglet/daemonset.yaml
  instrumentor/instrumentor.go
  instrumentor/internal/webhook_env_injector/webhook_env_injector.go
  k8sutils/go.mod
  k8sutils/pkg/feature/feature.go
  k8sutils/pkg/feature/feature_test.go
  k8sutils/pkg/service/service.go
  k8sutils/pkg/version/version.go
  odiglet/odiglet.go
  odiglet/pkg/ebpf/sdks/go.go
  odiglet/pkg/instrumentation/instrumentlang/dotnet.go
  odiglet/pkg/instrumentation/instrumentlang/java.go
  odiglet/pkg/instrumentation/instrumentlang/nodejs.go
  odiglet/pkg/instrumentation/instrumentlang/python.go
  tests/common/assert/pipeline-ready.yaml
  tests/e2e/cli-upgrade/assert-odigos-upgraded.yaml
Labels: enhancement

#2546 Add `ui-pagination-limit` to `odigos config set` CLI command
  cli/cmd/config.go
  common/consts/consts.go
  docs/cli/odigos_config.mdx
Labels: enhancement

#2537 Instances in UI - fetch all in a single query
  api/odigos/v1alpha1/instrumentationinstance_types.go
  frontend/graph/generated.go
  frontend/graph/model/models_gen.go
  frontend/graph/schema.graphqls
  frontend/graph/schema.resolvers.go
  frontend/services/destinations.go
  frontend/services/sources.go
  frontend/services/utils.go
  frontend/webapp/graphql/queries/source.ts
  frontend/webapp/hooks/destinations/usePotentialDestinations.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
  helm/odigos/values.yaml
Labels: frontend

#2540 Change label->Source migration to only take effect if a Source doesn't already exist
  cli/cmd/sources.go
  docs/cli/odigos_sources.mdx
  docs/cli/odigos_sources_delete.mdx
  docs/cli/odigos_sources_update.mdx
  docs/pipeline/sources/introduction.mdx
  docs/pipeline/sources/update.mdx
  instrumentor/controllers/workloadmigrations/controllers.go
  tests/e2e/source/README.md
  tests/e2e/source/chainsaw-test.yaml
Labels: bug

#2557 Bugfix/odigos instrumentor leader election error
  instrumentor/controllers/manager.go
  tests/chaos/README.md
  tests/chaos/experiments/network-latency.yaml
  tests/chaos/network-latency/leader-election/chainsaw-test.yaml
Labels: bug

#2559 Add links to api/k8sconsts in API docs
  api/genref-config.yaml
  docs/api-reference/odigos.io.v1alpha1.mdx
Labels: documentation

#2570 fix: dependabot yarn -> npm
  .github/dependabot.yml
Labels: bug, cicd

#2562 operator+cli: Change how component image references are set
  api/k8sconsts/consts.go
  cli/cmd/config.go
  cli/cmd/install.go
  cli/cmd/login.go
  cli/cmd/logout.go
  cli/cmd/profile.go
  cli/cmd/resources/autoscaler.go
  cli/cmd/resources/datacollection.go
  cli/cmd/resources/instrumentor.go
  cli/cmd/resources/keyvalproxy.go
  cli/cmd/resources/managers.go
  cli/cmd/resources/odiglet.go
  cli/cmd/resources/odigosconfig.go
  cli/cmd/resources/odigosdeployment.go
  cli/cmd/resources/odigospro/manager.go
  cli/cmd/resources/owntelemetry.go
  cli/cmd/resources/resourcemanager/resourcemanager.go
  cli/cmd/resources/scheduler.go
  cli/cmd/resources/ui.go
  cli/cmd/upgrade.go
  cli/pkg/containers/name.go
  cli/pkg/containers/name_test.go
  cli/pkg/kube/client.go
  common/consts/consts.go
  common/odigos_config.go
  docs/cli/odigos_install.mdx
  operator/Makefile
  operator/bundle/manifests/odigos-operator.clusterserviceversion.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/role.yaml
  operator/internal/controller/odigos_controller.go
Labels: enhancement

#2564 GitHub workflows grooming
  .github/actions/build/cli/action.yml
  .github/actions/nightly/report/action.yml
  .github/workflows/build-dev-images.yml
  .github/workflows/chaos-tests.yml
  .github/workflows/cross-cloud-tests.yaml
  .github/workflows/nightly.yml
  .github/workflows/run-chaos-tests.yml
  .github/workflows/run-cross-cloud-tests.yml
  Makefile
  tests/chaos/common/install_chaos_mesh.sh
  tests/chaos/network-latency/leader-election/chainsaw-test.yaml
  tests/e2e/helm-chart/chainsaw-test.yaml
Labels: cicd

#2591 unify publish modules workflow to push to gcp and dockerhub in the same flow
  .github/workflows/publish-modules-artifactregistry.yml
  .github/workflows/publish-modules.yml
Labels: cicd

#2605 feat: derive rule-type in UI backend
  frontend/graph/generated.go
  frontend/graph/model/models_gen.go
  frontend/graph/schema.graphqls
  frontend/services/instrumentationrule.go
  frontend/webapp/graphql/mutations/instrumentation-rule.ts
  frontend/webapp/graphql/queries/instrumentation-rules.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/types/index.ts
  frontend/webapp/types/instrumentation-rules.ts
Labels: enhancement, frontend

#2611 ci: fix flaky UI tests
  frontend/webapp/cypress.config.ts
  frontend/webapp/cypress/functions/index.ts
Labels: frontend, cicd

#2612 Fix nightly workflow references
  .github/actions/chaos-tests/action.yml
  .github/actions/cross-cloud-tests/action.yml
  .github/actions/nightly/report/action.yml
  .github/workflows/chaos-tests.yml
  .github/workflows/cross-cloud-tests.yaml
  .github/workflows/nightly.yml
  .github/workflows/run-chaos-tests.yml
  .github/workflows/run-cross-cloud-tests.yml
  tests-infrastructure/terraform/aks/main.tf
  tests-infrastructure/terraform/aks/variables.tf
  tests-infrastructure/terraform/eks/variables.tf
  tests/chaos/network-latency/leader-election/chainsaw-test.yaml
Labels: bug, cicd

#2613 chore: bump UI deps
  frontend/webapp/app/(overview)/layout.tsx
  frontend/webapp/app/(setup)/choose-destination/page.tsx
  frontend/webapp/app/(setup)/choose-sources/page.tsx
  frontend/webapp/app/page.tsx
  frontend/webapp/components/lib-imports/overview-header.tsx
  frontend/webapp/components/lib-imports/setup-header.tsx
  frontend/webapp/cypress.config.ts
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/hooks/actions/useActionCRUD.ts
  frontend/webapp/hooks/config/useConfig.ts
  frontend/webapp/hooks/describe/useDescribe.ts
  frontend/webapp/hooks/destinations/useDestinationCRUD.ts
  frontend/webapp/hooks/destinations/useTestConnection.ts
  frontend/webapp/hooks/instrumentation-rules/useInstrumentationRuleCRUD.ts
  frontend/webapp/hooks/namespaces/useNamespace.ts
  frontend/webapp/hooks/notification/useSSE.ts
  frontend/webapp/hooks/sources/useSourceCRUD.ts
  frontend/webapp/hooks/tokens/useTokenCRUD.ts
  frontend/webapp/hooks/tokens/useTokenTracker.ts
  frontend/webapp/package.json
  frontend/webapp/store/useStatusStore.ts
  frontend/webapp/types/actions.ts
  frontend/webapp/types/config.ts
  frontend/webapp/utils/functions/actions.ts
  frontend/webapp/utils/functions/sources.ts
  frontend/webapp/yarn.lock
Labels: frontend

#2616 fix: broken tests in UI
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
Labels: bug

#2608 Create sqllite in UI pod
  cli/cmd/resources/ui.go
  frontend/Makefile
  frontend/go.mod
  frontend/go.sum
  frontend/main.go
  frontend/services/db/database.go
  frontend/services/db/models.go
  frontend/services/db/sqlite.go
  helm/odigos/templates/ui/deployment.yaml
Labels: enhancement, frontend

#2622 ci: UI E2E flakes
  .github/workflows/e2e.yaml
  destinations/logos/causely.svg
  frontend/webapp/cypress.config.ts
  frontend/webapp/cypress/.gitignore
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/e2e/04-destinations.cy.ts
  frontend/webapp/cypress/e2e/05-actions.cy.ts
  frontend/webapp/cypress/e2e/06-rules.cy.ts
  frontend/webapp/cypress/functions/index.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
  tests/common/apply/install-jaeger.yaml
  tests/common/assert/jaeger-installed.yaml
  tests/e2e/ui/chainsaw-test.yaml
Labels: bug, cicd

#2391 Process and performance improvements in runtime inspection logic
  odiglet/pkg/ebpf/distribution_matcher.go
  odiglet/pkg/kube/runtime_details/inspection.go
  procdiscovery/go.mod
  procdiscovery/pkg/inspectors/dotnet/dotnet.go
  procdiscovery/pkg/inspectors/golang/golang.go
  procdiscovery/pkg/inspectors/java/java.go
  procdiscovery/pkg/inspectors/langdetect.go
  procdiscovery/pkg/inspectors/mysql/mysql.go
  procdiscovery/pkg/inspectors/nginx/nginx.go
  procdiscovery/pkg/inspectors/nodejs/nodejs.go
  procdiscovery/pkg/inspectors/python/python.go
  procdiscovery/pkg/inspectors/utils/inspectUtils.go
  procdiscovery/pkg/process/process.go
Labels: enhancement

#2647 [GEN-2129]: add TelemetryHub destination
  common/config/root.go
  common/config/telemetryhub.go
  common/dests.go
  destinations/data/telemetryhub.yaml
  destinations/logos/telemetryhub.svg
  docs/backends-overview.mdx
  docs/backends/telemetryhub.mdx
  docs/mint.json
Labels: destinations

#2644 [GEN-2152]: add Checkly destination
  common/config/checkly.go
  common/config/root.go
  common/dests.go
  destinations/data/checkly.yaml
  destinations/logos/checkly.svg
  docs/backends-overview.mdx
  docs/backends/checkly.mdx
  docs/mint.json
Labels: destinations

#2648 [GEN-1936]: add OpenObserve destination
  common/config/openobserve.go
  common/config/root.go
  common/dests.go
  destinations/data/openobserve.yaml
  destinations/logos/openobserve.svg
  docs/backends-overview.mdx
  docs/backends/openobserve.mdx
  docs/mint.json
Labels: destinations

#2649 Bump UI-Kit to 0.0.20
  frontend/webapp/cypress.config.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
Labels: frontend

#2653 [GEN-2127]: add Seq destination
  cli/cmd/resources/ui.go
  common/config/root.go
  common/config/seq.go
  common/dests.go
  destinations/data/seq.yaml
  destinations/logos/seq.svg
  docs/backends-overview.mdx
  docs/backends/seq.mdx
  docs/mint.json
  helm/odigos/templates/ui/role.yaml
Labels: destinations
