Repository odigos-io/odigos, pull requests merged in 2025-04, with the labels that each got.

#2666 [GEN-1942]: add Alibaba Cloud destination
  common/config/alibabacloud.go
  common/config/root.go
  common/dests.go
  destinations/data/alibabacloud.yaml
  destinations/logos/alibabacloud.svg
  docs/backends-overview.mdx
  docs/backends/alibabacloud.mdx
  docs/mint.json
Labels: destinations

#2663 [GEN-2125]: add Observe destination
  common/config/observe.go
  common/config/root.go
  common/dests.go
  destinations/data/observe.yaml
  destinations/logos/observe.svg
  docs/backends-overview.mdx
  docs/backends/observe.mdx
  docs/mint.json
Labels: destinations

#2664 [GEN-2130]: add Tingyun destination
  common/config/root.go
  common/config/tingyun.go
  common/dests.go
  destinations/data/tingyun.yaml
  destinations/logos/tingyun.svg
  docs/backends-overview.mdx
  docs/backends/tingyun.mdx
  docs/mint.json
Labels: destinations

#2665 [GEN-1948]: add Bonree ONE destination
  common/config/bonree.go
  common/config/root.go
  common/dests.go
  destinations/data/bonree.yaml
  destinations/logos/bonree.svg
  docs/backends-overview.mdx
  docs/backends/bonree.mdx
  docs/mint.json
Labels: destinations

#2668 [GEN-2131]: add Oracle Cloud destination
  common/config/oracle.go
  common/config/root.go
  common/dests.go
  destinations/data/oracle.yaml
  destinations/load.go
  destinations/logos/oracle.svg
  docs/backends-overview.mdx
  docs/backends/oracle.mdx
  docs/mint.json
Labels: destinations

#2676 fix: docs crash
  destinations/data/awscloudwatch.yaml
  docs/backends/awscloudwatch.mdx
Labels: bug, documentation

#2675 [GEN-1935]: add OneUptime destination
  common/config/oneuptime.go
  common/config/root.go
  common/dests.go
  destinations/data/oneuptime.yaml
  destinations/logos/oneuptime.svg
  docs/backends-overview.mdx
  docs/backends/oneuptime.mdx
  docs/mint.json
Labels: destinations

#2679 [GEN-2472]: add VictoriaMetrics destination
  collector/builder-config.yaml
  collector/odigosotelcol/components.go
  collector/odigosotelcol/go.mod
  collector/odigosotelcol/go.sum
  common/config/root.go
  common/config/victoriametricscloud.go
  common/dests.go
  destinations/data/victoriametricscloud.yaml
  destinations/logos/victoriametrics.svg
  docs/backends-overview.mdx
  docs/backends/victoriametricscloud.mdx
  docs/mint.json
Labels: destinations

#2681 ci: attempt to improve flake in UI tests
  frontend/webapp/app/(overview)/layout.tsx
  frontend/webapp/app/(setup)/layout.tsx
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  frontend/webapp/cypress/functions/index.ts
  frontend/webapp/package.json
  frontend/webapp/yarn.lock
Labels: cicd

#2704 fix: UI SSE modified events
  .gitignore
  frontend/webapp/app/(overview)/layout.tsx
  frontend/webapp/app/(setup)/layout.tsx
  frontend/webapp/hooks/notification/useSSE.ts
  frontend/webapp/package.json
  frontend/webapp/tsconfig.json
  frontend/webapp/yarn.lock
Labels: bug, frontend

#2732 feat: auto-instrument PHP versions 8+
  common/lang_detection.go
  distros/distro/oteldistribution.go
  distros/oteldistributions.go
  distros/yamls/php-community.yaml
  instrumentor/controllers/agentenabled/pods_webhook.go
  instrumentor/controllers/agentenabled/podswebhook/env.go
  instrumentor/controllers/agentenabled/podswebhook/otelresource.go
  instrumentor/controllers/agentenabled/sync.go
  instrumentor/internal/webhook_env_injector/webhook_env_injector.go
  instrumentor/sdks/sdks.go
  k8sutils/pkg/container/container.go
  odiglet/Dockerfile
  odiglet/Dockerfile.rhel
  odiglet/debug.Dockerfile
  procdiscovery/pkg/inspectors/java/java.go
  procdiscovery/pkg/inspectors/nodejs/nodejs.go
  procdiscovery/pkg/inspectors/php/php.go
  procdiscovery/pkg/inspectors/utils/inspectUtils.go
  procdiscovery/pkg/process/process.go
Labels: enhancement

#2760 fix: runtime version is not available for agent injection
  instrumentor/controllers/agentenabled/sync.go
Labels: bug

#2762 chore: bump PHP agent to v0.0.2
  odiglet/Dockerfile
Labels: php

#2766 Tag fix .values file
  helm/odigos/values.yaml
Labels: bug

#2767 Ci tag page limit fix
  .github/workflows/release-artifactregistry.yml
Labels: cicd

#2770 e2e: increase Odigos installed assertion timeout
  tests/e2e/helm-chart/chainsaw-test.yaml
Labels: cicd

#2768 Fix missing key error in grpc dest
  common/config/genericotlp.go
Labels: bug

#2777 ci: notify slack on success / failure of offset check pre release
  .github/workflows/publish-modules.yml
Labels: cicd

#2771 docs: generate rbac permissions
  .github/workflows/generated-docs.yaml
  Makefile
  docs/mint.json
  docs/permissions.mdx
  scripts/rbac-docgen/go.mod
  scripts/rbac-docgen/go.sum
  scripts/rbac-docgen/main.go
Labels: documentation

#2775 feat: add PHP documentation
  .gitignore
  docs/images/demo_architecture.png
  docs/instrumentations/overview.mdx
  docs/instrumentations/php/enrichment.mdx
  docs/instrumentations/php/native.mdx
  docs/mint.json
  docs/quickstart/introduction.mdx
  docs/snippets/languages-card.mdx
  docs/telemetry-types.mdx
  docs/vmagent/quickstart/introduction.mdx
Labels: documentation, php

#2776 Avoid JAVA_OPTS env profile
  cli/cmd/config.go
  common/consts/consts.go
  common/odigos_config.go
  docs/cli/odigos_config.mdx
  helm/odigos/templates/odigos-config-cm.yaml
  helm/odigos/values.yaml
  instrumentor/controllers/agentenabled/pods_webhook.go
  instrumentor/internal/webhook_env_injector/webhook_env_injector.go
  profiles/aggregators/kratos.go
  profiles/allprofiles.go
  profiles/instrumentation/envvar_injection.go
Labels: java

#2782 fix: Align helm to CLI by setting default imagePrefix to our registry
  .vscode/settings.json
  cli/cmd/install.go
  cli/cmd/upgrade.go
  cli/pkg/containers/name_test.go
  helm/odigos/templates/_helpers.tpl
  helm/odigos/templates/odigos-config-cm.yaml
Labels: bug

#2765 ci: add PHP e2e tests (and support multi-arch)
  frontend/webapp/cypress/constants/index.ts
  frontend/webapp/cypress/e2e/03-sources.cy.ts
  odiglet/Dockerfile
  tests/common/apply/generate-traffic-job.yaml
  tests/common/apply/install-simple-demo.yaml
  tests/common/assert/odigos-upgraded.yaml
  tests/common/assert/simple-demo-installed.yaml
  tests/common/assert/simple-demo-instrumented-full.yaml
  tests/common/assert/simple-demo-instrumented.yaml
  tests/common/assert/simple-demo-runtime-detected.yaml
  tests/common/queries/context-propagation-reported.yaml
  tests/common/queries/context-propagation.yaml
  tests/common/queries/resource-attributes.yaml
  tests/common/queries/span-attributes-reported.yaml
  tests/common/queries/span-attributes.yaml
  tests/common/queries/wait-for-trace-reported.yaml
  tests/common/queries/wait-for-trace.yaml
  tests/common/simple_trace_db_query_runner.sh
  tests/e2e/cli-upgrade/chainsaw-test.yaml
  tests/e2e/cli-upgrade/queries/resource-attributes.yaml
  tests/e2e/cli-upgrade/queries/span-attributes.yaml
  tests/e2e/helm-chart/chainsaw-test.yaml
  tests/e2e/helm-chart/queries/context-propagation.yaml
  tests/e2e/helm-chart/queries/resource-attributes.yaml
  tests/e2e/helm-chart/queries/span-attributes.yaml
  tests/e2e/helm-chart/queries/wait-for-trace.yaml
  tests/e2e/multi-apps/chainsaw-test.yaml
  tests/e2e/multi-apps/queries/context-propagation.yaml
  tests/e2e/multi-apps/queries/resource-attributes.yaml
  tests/e2e/multi-apps/queries/span-attributes.yaml
  tests/e2e/multi-apps/queries/wait-for-trace.yaml
  tests/e2e/source/01-sources.yaml
  tests/e2e/source/01-workloads.yaml
  tests/e2e/source/02-workloads.yaml
  tests/e2e/source/03-workloads.yaml
  tests/e2e/source/04-workloads.yaml
  tests/e2e/source/05-assert-runtime-detected.yaml
  tests/e2e/source/05-workloads.yaml
  tests/e2e/source/06-workloads.yaml
  tests/e2e/source/07-workloads.yaml
  tests/e2e/source/08-assert-runtime-detected.yaml
  tests/e2e/source/08-workloads-2.yaml
  tests/e2e/source/08-workloads.yaml
  tests/e2e/source/09-assert-runtime-detected.yaml
  tests/e2e/source/09-workloads.yaml
  tests/e2e/source/10-workloads.yaml
  tests/e2e/source/11-workloads.yaml
  tests/e2e/source/chainsaw-test.yaml
  tests/e2e/source/queries/context-propagation-2.yaml
  tests/e2e/source/queries/resource-attributes.yaml
  tests/e2e/source/queries/span-attributes-2.yaml
  tests/e2e/source/queries/span-attributes.yaml
  tests/e2e/source/queries/wait-for-trace-2.yaml
  tests/e2e/ui/chainsaw-test.yaml
  tests/e2e/ui/odigos-ui.log
Labels: enhancement, cicd, php

#2799 fix: double env injections
  instrumentor/controllers/agentenabled/podswebhook/env.go
  instrumentor/controllers/agentenabled/podswebhook/otelresource.go
  instrumentor/internal/webhook_env_injector/webhook_env_injector.go
Labels: bug

#2794 fix: use the correct cli image for helm cleanup hook
  helm/odigos/templates/cleanup/cleanup-job.yaml
  helm/odigos/values.yaml
Labels: bug

#2802 feat: bump PHP agent to 0.0.6
  instrumentor/controllers/agentenabled/podswebhook/env.go
  odiglet/Dockerfile
  odiglet/Dockerfile.rhel
  odiglet/debug.Dockerfile
  procdiscovery/pkg/inspectors/php/php.go
Labels: php

#2804 chore: update PHP agent version to v0.0.7 in Dockerfiles
  odiglet/Dockerfile
  odiglet/Dockerfile.rhel
  odiglet/debug.Dockerfile
Labels: php
